source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in preflex.gemspec.
gemspec

gem "puma"

gem "sqlite3"

gem "bootsnap"
gem "sprockets-rails"
gem "gem-release"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
